
rectangular_cavity_modes: rectangular_cavity_modes.F90
	$(FC) $(FLAGS) -o rectangular_cavity_modes rectangular_cavity_modes.F90 $(LIBS)
	mv rectangular_cavity_modes $(EXECUTABLE_DIR)/GGI_rectangular_cavity_modes

clean:
	rm -f *.o
	rm -f rectangular_cavity_modes
