skin_depth: skin_depth.F90 
	$(FC) $(FLAGS) -o skin_depth skin_depth.F90 $(GGI_LIBS) $(LIBS)
	mv skin_depth $(EXECUTABLE_DIR)/GGI_skin_depth

#clean		
clean:
	( rm -f *.o ; rm -f *.mod ; rm -f skin_depth)





