
rectangular_waveguide_modes: rectangular_waveguide_modes.F90
	$(FC) $(FLAGS) -o rectangular_waveguide_modes rectangular_waveguide_modes.F90 $(LIBS)
	mv rectangular_waveguide_modes $(EXECUTABLE_DIR)/GGI_rectangular_waveguide_modes

clean:
	rm -f *.o
	rm -f rectangular_waveguide_modes
